server:

  addr: 0.0.0.0
  port: 8899

  # if auth = true, the request header must carry 'Username' and 'Password'
  auth: false
  accounts:
    - username: root
      password: 123456

  # https
  tls: false
  cert-file: cert.pem
  key-file: private.key

  # console print
  debug: true

log:

  path: ./logs
  size: 1
  age: 7
  backups: 1000

dbs:

  - name: testDB
    type: mysql
    dsn: root:123456@tcp(127.0.0.1:3306)/test_db?charset=utf8mb4&parseTime=True&loc=Local

    groups:

      - name: testGroup
        format: lowerCamel
        apis:

            # API /query/testDB/testGroup/listByIdOrName
          - name: listByIdOrName
            sql: select * from test where 0=0 {#name} and name like {name} {/name} {#id} and id = {id} {/id} {#size} limit {size} {/size}

            # API /query/testDB/testGroup/listByIds
          - name: listByIds
            sql: select * from test where id in {ids}

            # API /command/testDB/testGroup/editNameById
          - name: editNameById
            sql: update test set name = {name} where id = {id} limit 1