server:
  addr: 0.0.0.0
  port: 8899
  tls: false
  cert-file: cert.pem
  key-file: private.key
log:
  path: ./logs
  size: 1
  age: 7
  backups: 1000
dbs:
  - name: test_db
    type: mysql
    dsn: root:123456@tcp(127.0.0.1:3306)/test_db?charset=utf8mb4&parseTime=True&loc=Local
    apis:
      - service: test
        method: list
        sql: select * from test where 0=0 {#name} and name like {name} {/name} {#id} and id = {id} {/id} {#size} limit {size} {/size}
        lower-camel: true
        debug: true